/**
 * Seeds the reward catalogue for the Tickets app (see the ticket bands
 * in the family reward system). Idempotent: re-running updates each row
 * in place. Run AFTER the ApiStack deploy has created wainwright-rewards:
 *   AWS_PROFILE=email AWS_REGION=us-east-1 npx tsx scripts/seed-rewards.ts
 */
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";
import { REWARD_EMOJI } from "./ticket-emoji";

const ddb = DynamoDBDocumentClient.from(new DynamoDBClient({}));

interface SeedReward {
  reward_id: string;
  title: string;
  description: string | null;
  ticket_cost: number;
  /** What the prize actually costs, in whole pence (admin-only).
   * Day-out prices are the CHILD's share only — parents absorb their own
   * tickets. Checked against official sites Sept 2026. */
  cost_pence: number | null;
  /** Icon filename under ticket-icons/ in the site bucket (optional).
   * Defaults are placeholder PNGs generated by scripts/gen-ticket-card-icons.ts
   * — swap for real photos via the admin portal any time. */
  icon: string | null;
  /** Fallback emoji shown when there's no photo. Defaults from
   * ticket-emoji.ts REWARD_EMOJI when omitted. */
  emoji?: string;
  /** How redemptions are limited (see task-routes.ts RewardRow):
   *   stock      — shared family pool, stock_remaining left
   *   period     — max 1 per child per window (week/month/summer/term/year)
   *   snack_stock — live portions from the Wainsbury's integration API
   *   unlimited  — no cap */
  limit_type: "unlimited" | "stock" | "period" | "snack_stock";
  stock_remaining?: number;
  period?: "week" | "month" | "summer" | "term" | "year";
  snack_product_slug?: string;
}

const REWARDS: SeedReward[] = [
  // 5 tickets — pocket-money treats
  { reward_id: "candy", title: "Candy", description: "A sweet treat from the multipack bag", ticket_cost: 5, cost_pence: 5, icon: "candy.png", limit_type: "stock", stock_remaining: 100 },
  { reward_id: "temporary-tattoo", title: "Temporary tattoo", description: "Pick a design — wears off in a few days", ticket_cost: 5, cost_pence: 5, icon: "temporary-tattoo.png", limit_type: "stock", stock_remaining: 150 },
  { reward_id: "choose-a-song", title: "Choose a song", description: "You pick what's playing — car, home, wherever", ticket_cost: 5, cost_pence: 0, icon: "choose-a-song.png", limit_type: "unlimited" },
  { reward_id: "extra-screen-time", title: "5 minutes extra screen time", description: "5 minutes of bonus screen time, same day", ticket_cost: 5, cost_pence: 0, icon: "extra-screen-time.png", limit_type: "unlimited" },
  // 10 tickets — small prizes
  { reward_id: "felt-tip-pen", title: "Felt tip pen", description: "A new felt tip pen for colouring", ticket_cost: 10, cost_pence: 25, icon: "felt-tip-pen.png", limit_type: "stock", stock_remaining: 24 },
  { reward_id: "sticker-sheet", title: "Sticker sheet", description: "A fresh sheet from the sticker drawer", ticket_cost: 10, cost_pence: 17, icon: "sticker-sheet.png", limit_type: "stock", stock_remaining: 19 },
  { reward_id: "small-toy", title: "Small toy", description: "Pick from the lucky-dip box", ticket_cost: 10, cost_pence: 10, icon: "small-toy.png", limit_type: "stock", stock_remaining: 150 },
  // 20 tickets — medium rewards
  { reward_id: "play-doh-tub", title: "Play-Doh tub", description: "A small tub — quiet play, no screen needed", ticket_cost: 20, cost_pence: 42, icon: "play-doh-tub.png", limit_type: "stock", stock_remaining: 10 },
  { reward_id: "movie-night-popcorn", title: "Movie night with popcorn", description: "Family film at home with a bag of popcorn each", ticket_cost: 20, cost_pence: 150, icon: "movie-night-popcorn.png", limit_type: "snack_stock", snack_product_slug: "butterkist-popcorn-toffee-6x20g" },
  { reward_id: "colouring-book", title: "Colouring book", description: "A new book from the pack", ticket_cost: 20, cost_pence: 65, icon: "colouring-book.png", limit_type: "stock", stock_remaining: 10 },
  { reward_id: "pick-a-movie", title: "Pick a movie", description: "You choose the next family film", ticket_cost: 20, cost_pence: 0, icon: "pick-a-movie.png", limit_type: "unlimited" },
  { reward_id: "stay-up-late", title: "Stay up 15 minutes late", description: "15 extra minutes of awake time, weekend night", ticket_cost: 20, cost_pence: 0, icon: "stay-up-late.png", limit_type: "unlimited" },
  { reward_id: "trip-to-the-park", title: "Trip to the park", description: "A proper park visit — swings and all", ticket_cost: 20, cost_pence: 0, icon: "trip-to-the-park.png", limit_type: "unlimited" },
  // 40 tickets — £1 rewards
  { reward_id: "ice-cream-treat", title: "Ice cream treat", description: "Ice cream from the van or the local shop", ticket_cost: 40, cost_pence: 100, icon: "ice-cream-treat.png", limit_type: "period", period: "month" },
  { reward_id: "bubble-wand", title: "Bubble wand", description: "A new bubble wand for the garden", ticket_cost: 40, cost_pence: 100, icon: "bubble-wand.png", limit_type: "period", period: "summer" },
  { reward_id: "choose-dinner", title: "Choose dinner", description: "You pick what the family eats that night", ticket_cost: 40, cost_pence: 0, icon: "choose-dinner.png", limit_type: "period", period: "week" },
  // 60 tickets — proper prizes
  { reward_id: "abbey-pumping-station", title: "Abbey Pumping Station", description: "Leicester's old steam engines — free most days!", ticket_cost: 60, cost_pence: 300, icon: "abbey-pumping-station.png", limit_type: "period", period: "term" },
  { reward_id: "happy-meal-treat", title: "Happy Meal treat", description: "Your own Happy Meal (or equivalent)", ticket_cost: 60, cost_pence: 465, icon: "happy-meal-treat.png", limit_type: "period", period: "month" },
  { reward_id: "new-book", title: "New book", description: "Pick a new book of your own", ticket_cost: 60, cost_pence: 550, icon: "new-book.png", limit_type: "period", period: "term" },
  { reward_id: "cinema-trip", title: "Cinema trip", description: "Your ticket + one parent (watch for free-ticket offers!)", ticket_cost: 60, cost_pence: 550, icon: "cinema-trip.png", limit_type: "period", period: "month" },
  { reward_id: "craft-kit", title: "Craft kit", description: "A full craft kit to keep you busy all afternoon", ticket_cost: 60, cost_pence: 600, icon: "craft-kit.png", limit_type: "period", period: "term" },
  { reward_id: "king-richard-iii-centre", title: "King Richard III Centre", description: "Leicester's own king — see where he was found", ticket_cost: 60, cost_pence: 625, icon: "king-richard-iii-centre.png", limit_type: "period", period: "term" },
  // 80 tickets — event treats
  { reward_id: "soft-play-session", title: "Soft play session", description: "Your entry + one parent", ticket_cost: 80, cost_pence: 795, icon: "soft-play-session.png", limit_type: "period", period: "month" },
  { reward_id: "invite-a-friend-over", title: "Invite a friend over", description: "A friend comes to play (arranged with Mum/Dad)", ticket_cost: 80, cost_pence: 0, icon: "invite-a-friend-over.png", limit_type: "period", period: "term" },
  // 100 tickets — big prizes
  { reward_id: "conkers-trip", title: "Conkers trip", description: "A day at Conkers — woodland, mazes and trains", ticket_cost: 100, cost_pence: 1100, icon: "conkers-trip.png", limit_type: "period", period: "term" },
  { reward_id: "big-toy", title: "Big toy", description: "One big toy (up to £15)", ticket_cost: 100, cost_pence: 1500, icon: "big-toy.png", limit_type: "period", period: "term" },
  // 150 tickets — the big save-up (child ticket only)
  { reward_id: "great-central-railway", title: "Great Central Railway", description: "A ride on a real steam train", ticket_cost: 150, cost_pence: 1300, icon: "great-central-railway.png", limit_type: "period", period: "year" },
  { reward_id: "twinlakes-trip", title: "Twinlakes trip", description: "A whole day of rides and play barns", ticket_cost: 150, cost_pence: 1600, icon: "twinlakes-trip.png", limit_type: "period", period: "year" },
  { reward_id: "wicksteed-park-trip", title: "Wicksteed Park trip", description: "Rides, playground, and the big park at Kettering", ticket_cost: 150, cost_pence: 1760, icon: "wicksteed-park-trip.png", limit_type: "period", period: "year" },
  { reward_id: "twycross-zoo-trip", title: "Twycross Zoo trip", description: "The monkeys, the Gruffalo trail and everything else", ticket_cost: 150, cost_pence: 1950, icon: "twycross-zoo-trip.png", limit_type: "period", period: "year" },
  { reward_id: "space-centre-trip", title: "Space Centre trip", description: "Rockets, astronauts, and the planetarium — right here in Leicester", ticket_cost: 150, cost_pence: 2000, icon: "space-centre-trip.png", limit_type: "period", period: "year" },
  // 300 tickets — the mega band (child share only)
  { reward_id: "warwick-castle-trip", title: "Warwick Castle trip", description: "A big day at the castle — knights and all", ticket_cost: 300, cost_pence: 2900, icon: "warwick-castle-trip.png", limit_type: "period", period: "year" },
  { reward_id: "thorpe-park-trip", title: "Thorpe Park trip", description: "A big day of thrill rides", ticket_cost: 300, cost_pence: 3200, icon: "thorpe-park-trip.png", limit_type: "period", period: "year" },
  { reward_id: "alton-towers-trip", title: "Alton Towers trip", description: "The epic one — a whole day at the theme park", ticket_cost: 300, cost_pence: 4200, icon: "alton-towers-trip.png", limit_type: "period", period: "year" },
  { reward_id: "london-day-trip", title: "London day trip", description: "Train to London for a big day out (up to ~£30)", ticket_cost: 300, cost_pence: 2500, icon: "london-day-trip.png", limit_type: "period", period: "year" },
  { reward_id: "overnight-adventure", title: "Overnight adventure", description: "An overnight stay or camping trip", ticket_cost: 300, cost_pence: 5000, icon: "overnight-adventure.png", limit_type: "period", period: "year" },
];

const now = new Date().toISOString();
for (const reward of REWARDS) {
  await ddb.send(
    new PutCommand({
      TableName: "wainwright-rewards",
      Item: {
        ...reward,
        emoji: reward.emoji ?? REWARD_EMOJI[reward.reward_id] ?? null,
        stock_remaining: reward.limit_type === "stock" ? (reward.stock_remaining ?? 0) : null,
        period: reward.limit_type === "period" ? (reward.period ?? null) : null,
        snack_product_slug: reward.limit_type === "snack_stock" ? (reward.snack_product_slug ?? null) : null,
        enabled: true,
        created_at: now,
        updated_at: now,
      },
    })
  );
  console.log(`✓ ${reward.title} (${reward.ticket_cost} tickets, ${reward.cost_pence ?? "—"}p, ${reward.icon ?? "no icon"}, ${reward.limit_type}${reward.period ? ` ${reward.period}` : ""}${reward.stock_remaining !== undefined ? ` (${reward.stock_remaining} left)` : ""})`);
}
console.log(`\nSeeded ${REWARDS.length} rewards.`);
