#!/usr/bin/env bash
# Copy the Wainsbury's snack-integration token (generated by the shopping
# account's CDK stack) into the wainwright.fun account's secret so both apps
# share the same non-expiring token.
#
#   shopping account:  AWS_PROFILE=shopping  eu-west-2  (source of truth)
#   wainwright.fun:  AWS_PROFILE=email     us-east-1
#
# Run after both stacks have been deployed at least once.

set -euo pipefail

SHOPPING_SECRET_ARN="$(
  aws --profile shopping --region eu-west-2 \
    cloudformation describe-stacks \
    --stack-name ShoppingApiStack \
    --query "Stacks[0].Outputs[?OutputKey=='SnackIntegrationSecretArn'].OutputValue" \
    --output text
)"

TOKEN_JSON="$(
  aws --profile shopping --region eu-west-2 \
    secretsmanager get-secret-value \
    --secret-id "${SHOPPING_SECRET_ARN}" \
    --query SecretString --output text
)"

aws --profile email --region us-east-1 \
  secretsmanager put-secret-value \
  --secret-id wainsburys-integration-token \
  --secret-string "${TOKEN_JSON}"

echo "Token synced to the wainwright.fun account."
