/**
 * Shared DynamoDB → RootConfig transformation.
 *
 * Used by:
 *   - packages/infra/lambda/api.ts          (GET /config — generates apps.yaml)
 *   - packages/infra/scripts/generate-config.ts
 *   - packages/infra/lambda/site-rebuilder.ts (builds per-child resolved configs)
 *
 * This ensures the YAML generated by the API Lambda and the local script
 * are always identical, and that the site-rebuilder uses the same config
 * shape as the deploy script's resolveChildConfig().
 */

import type { RootConfig, Child, AppEntry, SystemApp, WebsiteEntry, AgeBand, Restriction } from "./config.js";

/** Raw DynamoDB row shapes (all fields are present after scan). */
export interface DbChild {
  subdomain: string;
  name: string;
  date_of_birth: string;
  color: string;
  avatar?: string;
  locked?: boolean;
  restriction_overrides?: unknown;
  blocked_apps?: string[];
}

export interface DbApp {
  bundle_id: string;
  name: string;
  type: "app" | "system";
  app_store_url?: string;
  category?: string;
  icon?: string;
  show_on_site?: boolean;
  min_age: number;
  enabled: boolean;
}

export interface DbWebsite {
  url: string;
  name: string;
  icon?: string;
  category?: string;
  min_age: number;
  enabled: boolean;
  child_subdomain?: string;
}

export interface DbTheme {
  from_age: number;
  theme: string;
  subtitle: string;
  restriction_overrides?: unknown;
}

export interface DbRestriction {
  key: string;
  value: boolean | number | string;
  type: "boolean" | "integer" | "real" | "string";
  overridable?: boolean;
}

export interface DbRows {
  children: DbChild[];
  apps: DbApp[];
  websites: DbWebsite[];
  themes: DbTheme[];
  restrictions: DbRestriction[];
}

/**
 * Transforms raw DynamoDB rows into a RootConfig (the in-memory shape
 * that packages/shared/scripts/{resolve,config}.ts consume).
 *
 * This is the single source of truth for how DynamoDB rows map to the
 * config model. Both the API Lambda and the local generate-config script
 * call this, so they can never diverge.
 */
export function buildRootConfig(rows: DbRows): RootConfig {
  const { children, apps, websites, themes, restrictions } = rows;

  // Sort themes by from_age ascending
  const sortedThemes = themes.sort((a, b) => a.from_age - b.from_age);

  // Theme bands — drive theme/subtitle only, never app membership
  const ageBands: AgeBand[] = sortedThemes.map((theme) => {
    const band: AgeBand = {
      from_age: theme.from_age,
      theme: theme.theme as AgeBand["theme"],
      subtitle: theme.subtitle,
    };
    if (theme.restriction_overrides) {
      band.restriction_overrides = theme.restriction_overrides as AgeBand["restriction_overrides"];
    }
    return band;
  });

  // All apps (regular + system) as flat lists keyed by their own min_age.
  // min_age is any age — it does not need to match a theme band's from_age.
  const toAppEntry = (a: DbApp): AppEntry => ({
    name: a.name,
    bundle_id: a.bundle_id,
    app_store_url: a.app_store_url ?? "",
    min_age: a.min_age,
    ...(a.category ? { category: a.category } : {}),
  });

  const toSystemAppEntry = (a: DbApp): SystemApp => ({
    bundle_id: a.bundle_id,
    name: a.name,
    min_age: a.min_age,
    ...(a.show_on_site !== undefined ? { show_on_site: a.show_on_site } : {}),
    ...(a.app_store_url ? { app_store_url: a.app_store_url } : {}),
    ...(a.icon ? { icon: a.icon } : {}),
    ...(a.category ? { category: a.category } : {}),
  });

  const allApps: AppEntry[] = apps
    .filter((a) => a.type === "app" && a.enabled)
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(toAppEntry);

  const allSystemApps: SystemApp[] = apps
    .filter((a) => a.type === "system" && a.enabled)
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(toSystemAppEntry);

  // Shared websites (personal websites are attached to their child below)
  const sharedWebsites: WebsiteEntry[] = websites
    .filter((w) => w.enabled && !w.child_subdomain)
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((w) => ({
      name: w.name,
      url: w.url,
      min_age: w.min_age,
      ...(w.icon ? { icon: w.icon } : {}),
      ...(w.category ? { category: w.category } : {}),
    }));

  // Children — with personal_websites attached
  const childEntries: Child[] = children
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((c) => {
      const entry: Child = {
        name: c.name,
        subdomain: c.subdomain,
        date_of_birth: c.date_of_birth,
        color: c.color as Child["color"],
        locked: c.locked !== false,
      };
      if (c.avatar) entry.avatar = c.avatar;
      if (c.restriction_overrides) {
        entry.restriction_overrides = c.restriction_overrides as Child["restriction_overrides"];
      }
      if (c.blocked_apps && c.blocked_apps.length > 0) {
        entry.blocked_apps = c.blocked_apps;
      }
      // Personal websites assigned to this child (bypass age bands)
      const personalWebsites: WebsiteEntry[] = websites
        .filter((w) => w.enabled && w.child_subdomain === c.subdomain)
        .sort((a, b) => a.name.localeCompare(b.name))
        .map((w) => {
          const wEntry: WebsiteEntry = {
            name: w.name,
            url: w.url,
          };
          if (w.icon) wEntry.icon = w.icon;
          if (w.category) wEntry.category = w.category;
          return wEntry;
        });
      if (personalWebsites.length > 0) entry.personal_websites = personalWebsites;
      return entry;
    });

  const restrictionEntries: Restriction[] = restrictions
    .sort((a, b) => a.key.localeCompare(b.key))
    .map((r) => {
      const entry: Restriction = {
        key: r.key,
        value: r.value,
        type: r.type,
      };
      if (r.overridable) entry.overridable = r.overridable;
      return entry;
    });

  return {
    domain: "wainwright.fun",
    site: {
      profile_button_text: "Install iPad Profile",
    },
    profile: {
      organization: "Wainwright Family",
    },
    restrictions: restrictionEntries,
    children: childEntries,
    apps: allApps,
    system_apps: allSystemApps,
    websites: sharedWebsites,
    age_bands: ageBands,
  };
}
